{{- define "rpa-mit-manual-templates.container" -}}
ports:
- name: http
  containerPort: {{ .Values.container.port }}
  protocol: TCP
livenessProbe: {{ include "adp-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4 }}
readinessProbe: {{ include "adp-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4 }}
{{- end -}}