services:
  rpa-mit-manual-templates:
    build:
      context: .
      target: production
    image: rpa-mit-manual-templates
    container_name: rpa-mit-manual-templates
    environment:
      APPINSIGHTS_CLOUDROLE: ${rpa-mit-manual-templates-local}
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      REQUEST_HOST: ${REQUEST_HOST}
      CLOUD_INSTANCE: ${CLOUD_INSTANCE}
      TENANT_ID: ${TENANT_ID}
      CLIENT_ID: ${CLIENT_ID}
      REDIRECT_URI: ${REDIRECT_URI}
      POST_LOGOUT_REDIRECT_URI: ${POST_LOGOUT_REDIRECT_URI}
      EXPRESS_SESSION_SECRET: Enter_the_Express_Session_Secret_Here
      AUDIENCE: ${AUDIENCE}
      SCOPES: ${SCOPES}
      CLIENT_SECRET: ${CLIENT_SECRET}