services:
  rpa-mit-manual-templates:
    build:
      context: .
      target: production
    image: rpa-mit-manual-templates
    container_name: rpa-mit-manual-templates
    environment:
      APPINSIGHTS_CLOUDROLE: rpa-mit-manual-templates-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
