- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: CLOUD_INSTANCE
  value: "{{servicename}}-CLOUD-INSTANCE" 
  type: "keyvault"
- key: TENANT_ID
  value: "{{servicename}}-TENANT-ID" 
  type: "keyvault"
- key: CLIENT_ID
  value: "{{servicename}}-CLIENT-ID" 
  type: "keyvault"
- key: CLIENT_SECRET
  value: "{{servicename}}-CLIENT-SECRET 
  type: "keyvault"
- key: REDIRECT_URI
  value: "{{servicename}}-REDIRECT-URI" 
  type: "keyvault"
- key: POST_LOGOUT_REDIRECT_URI
  value: "{{servicename}}-POST-LOGOUT-REDIRECT-URI" 
  type: "keyvault"
- key: EXPRESS_SESSION_SECRET
  value: "{{servicename}}-EXPRESS-SESSION-SECRET" 
  type: "keyvault"
- key: SCOPE
  value: "{{servicename}}-SCOPE" 
  type: "keyvault"
- key: REQUEST_HOST
  value: "{{servicename}}-REQUEST-HOST" 
  type: "keyvault"