- key: APPINSIGHTS__CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: CLOUD__INSTANCE
  value: "{{servicename}}-CLOUD-INSTANCE" 
  type: "keyvault"
- key: TENANT__ID
  value: "{{servicename}}-TENANT-ID" 
  type: "keyvault"
- key: CLIENT__ID
  value: "{{servicename}}-CLIENT-ID" 
  type: "keyvault"
- key: CLIENT__SECRET
  value: "{{servicename}}-CLIENT-SECRET"
  type: "keyvault"
- key: REDIRECT__URI
  value: "{{servicename}}-REDIRECT-URI" 
  type: "keyvault"
- key: POST__LOGOUT__REDIRECT__URI
  value: "{{servicename}}-POST-LOGOUT-REDIRECT-URI" 
  type: "keyvault"
- key: EXPRESS__SESSION__SECRET
  value: "{{servicename}}-EXPRESS-SESSION-SECRET" 
  type: "keyvault"
- key: SCOPES
  value: "{{servicename}}-SCOPES" 
  type: "keyvault"
- key: REQUEST__HOST
  value: "{{servicename}}-REQUEST-HOST" 
  type: "keyvault"
